In [244]:
import numpy as np
import pandas as pd

##### Load Data

In [245]:
df=pd.read_csv(r'anime.csv') # r lagane se path me '\' hota he use '\n' escape sequence jo ki new line ya '\t' tab nahi smjata
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [246]:
def extract_episode(txt):
    flag=False
    episodes=""
    for i in txt:
        if i=='(':
            flag=True
            continue
        if flag and i==' ':
            break
        if flag:
            episodes+=i
    return episodes

In [247]:
def extract_date(txt):
    
    flag=False
    ans=""
    
    for ch in str(txt):
        
        if ch==')':
            flag=True
            continue
        
        if flag and ch==',':break
        if flag:ans+=ch
        
    last=ans.rfind(' ')
    
    if last!=-1:ans=ans[:last+5]
        
    return ans

In [250]:
def get_total_months(time_str):
    time_str = str(time_str)
    
    if '-' not in time_str:
        return 0
        
    m_dict = {"Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6, 
              "Jul": 7, "Aug": 8, "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12}
    
    try:
        parts = time_str.split('-')
        start = parts[0].strip()
        end = parts[1].strip()
        
        s_m, s_y = m_dict.get(start[:3], 0), int(start[-4:])
        e_m, e_y = m_dict.get(end[:3], 0), int(end[-4:])
        
        if s_m == 0 or e_m == 0:
            return 0
            
        total_months = (e_y - s_y) * 12 + (e_m - s_m)
        
        return total_months if total_months > 0 else 0
    except:
        return 0

In [ ]:
df['Episodes']=df['Title'].apply(extract_episode)
df['Episodes']=df['Episodes'].astype(int)
df['Total Time']=df['Title'].apply(extract_date)
df['Months']=df['Total Time'].apply(get_total_months)
df.head()

<class 'numpy.int64'>

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3

In [252]:
# Higesh Score
highest_score=df[df['Score']==df['Score'].max()]
highest_score

# Ye sahi kyu chala?

# df['Score'] == df['Score'].max() ek condition check karta hai. Ye har ek row ke paas jata hai aur dekhta hai ki kya uska score highest hai?

# Iske result mein ek True aur False ki list banti hai (jis row ka score max hai wahan True, baaki sab jagah False). Isko "Boolean Mask" kehte hain.

# Jab tu df[True/False wali list] paas karta hai, toh Pandas samajh jata hai ki tujhe Rows filter karni hain. Isliye wo sirf unhi rows ko bahar nikal ke deta hai jahan condition True thi.

# Short mein:

# Pehle wale mein tu direct value (number) daal raha tha, jisko Pandas column samajh baitha.

# Doosre wale mein tu Condition (==) daal raha hai, jisse Pandas rows filter karke deta hai.

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,15

In [253]:
# top 5 highest scoring anime
df[['Title','Score']].head()
# already sorted he data

                                               Title  Score
0  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [261]:
#highest episode count
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total Time,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47