# Series

* A Pandas Series is a one-dimensional, labeled array capable of holding data of any type (integers, strings, floats, Python objects, etc.). You can think of it as a single column in an Excel spreadsheet or a database table.
* index are called as labels

In [1]:
import pandas as pd
import numpy as np

In [2]:
my_list=[1,2,3,34]
labels=['a','b','c','d']
my_arr=np.array([1,2,3,4,4])
my_dic={1:10,2:23,3:"kedar"}

In [81]:
a=pd.Series(my_list) # Python list se series
b=pd.Series(my_arr) # numpay array se series
c=pd.Series(my_dic) # for dictionaries keys are their indexes
d=pd.Series(my_list,index=labels) #lenght of both should be same
print(a)
print(b)
print(c)
print(d)

0     1
1     2
2     3
3    34
dtype: int64
0    1
1    2
2    3
3    4
4    4
dtype: int64
1       10
2       23
3    kedar
dtype: object
a     1
b     2
c     3
d    34
dtype: int64

# Dataframe
* A Pandas DataFrame is a two-dimensional, size-mutable, and tabular data structure with labeled axes (rows and columns) in Python. It is the primary data structure used in the Pandas library and functions similarly to an Excel spreadsheet or a SQL table.

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
print(pd.DataFrame(data))
# df from python dictionaries

#     Name  Age      City  Salary
# 0   John   28  New York   65000
# 1   Anna   34     Paris   70000
# 2  Peter   29    Berlin   62000
# 3  Linda   42    London   85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
x=pd.DataFrame(data_list)
y=pd.DataFrame(data_list,columns=['a','b','c','d']) # df from python list
print(x)
print(y)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000
       a   b         c      d
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [6]:
print(x[0])
# print(y[0]) # this will give error because columns name is not '0;
print(y['a'])
print(y[['a','b']])

0     John
1     Anna
2    Peter
3    Linda
Name: 0, dtype: object
0     John
1     Anna
2    Peter
3    Linda
Name: a, dtype: object
       a   b
0   John  28
1   Anna  34
2  Peter  29
3  Linda  42

In [7]:
y["abcd"]=[1,2,4,5] # len should be same
y

       a   b         c      d  abcd
0   John  28  New York  65000     1
1   Anna  34     Paris  70000     2
2  Peter  29    Berlin  62000     4
3  Linda  42    London  85000     5

In [8]:
# y.drop('abcd') -->error
ab=y.drop('abcd',axis=1) # ya to ise kisi aur me save karo,y me koi changes nahi honge
print(ab)
print(y)
# y.drop('abcd',inplace=True,axis=1) # ab ye y se hi hat gaya coulmn
print(y)
# column name pehele hona chiye baki attributes ka posn kuch bhi ho skta he
y.drop([0,1],axis=0) # ab ye row hat gaye inplacae nahi he toh y me he pr jo ye return karega us se hat gaye

       a   b         c      d
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000
       a   b         c      d  abcd
0   John  28  New York  65000     1
1   Anna  34     Paris  70000     2
2  Peter  29    Berlin  62000     4
3  Linda  42    London  85000     5
       a   b         c      d  abcd
0   John  28  New York  65000     1
1   Anna  34     Paris  70000     2
2  Peter  29    Berlin  62000     4
3  Linda  42    London  85000     5

       a   b       c      d  abcd
2  Peter  29  Berlin  62000     4
3  Linda  42  London  85000     5

In [9]:
print(y.loc[0])
print()
print(y.loc[[0,1]])  # rows ka hi he par label based he,labels strings honge toh string do default toh numbers hote he
print()
print(y.iloc[3]) # rows ka hi he par index based he,labels row ke sttring bhi honge toh bhi iloc se 0,1,2 index se hi krna padega
print()
print(y.loc[1,'c']) # paris-->particular row col jaisa same numpy jaisa
print()

y.iloc[1:3, 1:3]   # position, end excluded
y.loc[1:2, 'b':'c'] # labels, end included
# same as numpy

a           John
b             28
c       New York
d          65000
abcd           1
Name: 0, dtype: object

      a   b         c      d  abcd
0  John  28  New York  65000     1
1  Anna  34     Paris  70000     2

a        Linda
b           42
c       London
d        85000
abcd         5
Name: 3, dtype: object

Paris

    b       c
1  34   Paris
2  29  Berlin

In [37]:
y.loc[[0,1]][['c','d']] #.loc[]-->rows  he  agla bracket columns
y[y['b']>30] # column be with values >30
y[(y['b']>30) & (y['c']=="Paris") ] # & use karte samy dono condn brackets me hona chahiye

      a   b      c      d  abcd
1  Anna  34  Paris  70000     2

## MISSING VALUES

In [38]:
newData = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df=pd.DataFrame(newData)
df.isna()
# A	B	C	D
# 0	False	True	False	False
# 1	False	False	False	True
# 2	True	False	False	True
# 3	False	False	True	True
# 4	False	False	True	False

df.isna().sum()
# 	0
# A	1
# B	1
# C	2
# D	3

df.isna().any() # ek bhi null hoga toh col ko true mark karega

#       0
# A	True
# B	True
# C	True
# D	True

A     True
B    False
C     True
D     True
dtype: bool

In [39]:
# row ke uppar chalta he
df2=df.dropna()
df2=df.dropna(thresh=3) # kam se kam 3 non null honi chahiye tab rahega
print(df) # df se kuch nahi hatega
print(df2)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0
     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [44]:
# dropna ----> row wise
# isna ----> col wise
# fillna ----> col wise

df.isna() # search
df.dropna() # remove

df.fillna(0) # filling null as zero
df.fillna(value=0) # pehli attribute default value hota he-->

			# print(df) # isme kuch fill na hoga naya df banana padega
			# inplace=true kar do naye df ki jarurat nahi padegi

val={'A':1,'B':2,'C':3,'D':4}
# val=[1,2,3,4] --->"value" parameter must be a scalar or dict,
df.fillna(df.mean())
df.fillna(value=val,inplace=True)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  4.0
2  1.0  3  3.0  4.0
3  4.0  4  3.0  4.0
4  5.0  5  3.0  5.0

# Merging Joining Concatination

## MERGING

In [45]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [76]:
a1=pd.merge(employees,salaries,on='employee_id',how='inner') # inner join type-->common included
a2=pd.merge(employees,salaries,on='employee_id',how='outer') # outer join type -->all included
a3=pd.merge(employees,salaries,on='employee_id',how='left') # left join type-->left wale ke sare ayenge
a4=pd.merge(employees,salaries,on='employee_id',how='right') # right join type-->right wale ke sare ayenge
print(employees)
print(salaries)
# new df return karega

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR
   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

## CONCATINATION

In [77]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})
df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [78]:
pd.concat([df1,df2])
print(df1)
print(df2)
# new df return karega
pd.concat([df1,df2],axis=1) # row wise

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

## JOINING

In [79]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [80]:
df1.join(df2) # ye  he -->default inner join
df1.join(df2,how='outer')
# new df return karega

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

# Group By 
* Group by object return krta he

In [126]:
data1 = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df1=pd.DataFrame(data1)
df1

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [127]:
cat=df1.groupby('Category')
print(type(cat)) # <class 'pandas.core.groupby.generic.DataFrameGroupBy'>
print(cat) # <pandas.core.groupby.generic.DataFrameGroupBy object at 0x7a7759399f10>
# object ko direct print nahi kar skte
for category,v in cat:
    print('Category:'+category)
    print(v)
    
print(cat['Sales'].sum())
# Category
# A    570
# B    930
# Name: Sales, dtype: int64

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7a775939a750>
Category:A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
Category:B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08
Category
A    570
B    930
Name: Sales, dtype: int64

### Group by multiple categories

In [128]:
dog=df1.groupby(['Category','Store'])
for i,v in dog:
    print(i)
    print(v)
    print()
    print()

print(dog['Sales'].sum())

# Category  Store
#       A            S1           220
#                     S2           350
#       B            S1      500
#                      S2          430
# Name: Sales, dtype: int64

('A', 'S1')
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
4        A    S1    120         8 2023-01-05


('A', 'S2')
  Category Store  Sales  Quantity       Date
2        A    S2    150        12 2023-01-03
6        A    S2    200        15 2023-01-07


('B', 'S1')
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
7        B    S1    300        25 2023-01-08


('B', 'S2')
  Category Store  Sales  Quantity       Date
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06


Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

## AGGREGATION
* columns ke sare values ko combine krke kuch methods lagana jaise mean medain mode

In [132]:
df1['Sales'].mean()
df1['Sales'].agg(['mean','max','min','median','std']) # mode nahi kar skte bas

mean      187.500000
max       300.000000
min       100.000000
median    190.000000
std        66.062741
Name: Sales, dtype: float64

# Pivot tables
* heat maps banande me use ayega

In [138]:
data2 = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df2 = pd.DataFrame(data2)

# print(df2)
df2['Month'] = df2['Date'].dt.month_name()
# print(df2)
df2['Quarter'] = 'Q' + df2['Date'].dt.quarter.astype(str)
# print(df2)

In [ ]:
xy=df2.pivot_table(index='Region',values='Sales',columns='Product') # values me mean ayega
# print(type(xy)) # <class 'pandas.core.frame.DataFrame'> 
xy

<class 'pandas.core.frame.DataFrame'>

Product      A      B      C      D
Region
East     395.8    NaN    NaN    NaN
North      NaN    NaN  547.4    NaN
South      NaN    NaN    NaN  524.2
West       NaN  635.2    NaN    NaN

In [147]:
# pivot2=df2.pivot_table(index='Region',columns='Product',values=['Sales','Units'])
# pivot2
df2.pivot_table(index='Region', columns='Product', values='Sales', aggfunc='mean')

Product      A      B      C      D
Region
East     395.8    NaN    NaN    NaN
North      NaN    NaN  547.4    NaN
South      NaN    NaN    NaN  524.2
West       NaN  635.2    NaN    NaN

In [150]:
pd.crosstab(df2['Region'], df2['Product']) # isme mean nahi hoga,count hoga

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# DataFrame Basic Operations

In [172]:
dfxy = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [173]:
print(dfxy.shape) # (5, 3)
print()
print(dfxy.columns) # Index(['A', 'B', 'C'], dtype='object')
print()
print(dfxy.info()) 
# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 5 entries, 0 to 4
# Data columns (total 3 columns):
#  #   Column  Non-Null Count  Dtype
# ---  ------  --------------  -----
#  0   A       5 non-null      int64
#  1   B       5 non-null      int64
#  2   C       5 non-null      int64
# dtypes: int64(3)
# memory usage: 252.0 bytes
# None
print()
print(dfxy.describe())
print()
print()

#                A                       B                    C
# count   5.000000   5.000000    5.000000
# mean   3.000000   30.000000  300.000000
# std       1.581139     15.811388    158.113883
# min      1.000000    10.000000   100.000000
# 25%    2.000000    20.000000  200.000000
# 50%    3.000000    30.000000  300.000000
# 75%    4.000000    40.000000  400.000000
# max     5.000000    50.000000  500.000000

dfxy['A']=dfxy['A']+10 # Assign nahi kiya toh changes nahi honge


# A
# 0	11
# 1	12
# 2	13
# 3	14
# 4	15

# dtype: int64

def square(x):
    return x**2

dfxy['B']=dfxy['B'].apply(square)
print(dfxy['B'])
print()

dfxy['D']=dfxy['B'].apply(lambda x:x*3)
print(dfxy['D'])
print()

(5, 3)

Index(['A', 'B', 'C'], dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes
None

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000


0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

0     300
1    1200
2    2700
3    4800
4    7500
Name: D, dtype: int64